[package]
name = "detect-duplicates"
version = "0.1.0"
edition = "2021"
description = "Detects and reports duplicate files in a file system"
license = "MIT"

[[bin]]
path = "src/main.rs"
name = "detect-duplicates"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }